# -*- coding: utf-8 -*-
{
    'name': 'Customer Map Tracking',
    'version': '1.0.0',
    'category': 'Extra Tools',
    'summary': 'Track customers / workers on map and open detail on click',
    'author': 'Generated by GPT',
    'website': '',
    'license': 'AGPL-3',
    'depends': [
        'base',
        'web',
        'web_leaflet_lib',
        'base_geoengine',
    ],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/customer_map_actions.xml',
        'views/customer_map_menus.xml',
        'views/customer_map_views.xml',
        # 'views/assets.xml',
    ],
    'assets': {
        'web.assets_backend': [
            # Leaflet CDN
            "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css",
            "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js",

            # Custom JS/XML
            'customer_map_tracking/static/src/js/map_dashboard.js',
            'customer_map_tracking/static/src/js/map_picker_field.js',
            'customer_map_tracking/static/src/xml/map_picker_templates.xml',
            'customer_map_tracking/static/src/css/map_styles.css',
        ],
    },
    'installable': True,
    'application': False,
}
